name: Analysis 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analysis:
    runs-on: ubuntu-latest

    env:
      DATAWRAPPER_API: ${{ secrets.DATAWRAPPER_API }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy matplotlib arviz pymc scipy statsmodels datawrapper

      - name: Run analysis script
        run: |
          python Interrupted.py
