name: Charts

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"    

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas geopandas numpy matplotlib datawrapper
    - name: Run script
      run: python Charts.py
      env:
        DATAWRAPPER_API: ${{ secrets.DATAWRAPPER_API }}
