name: data
on:
  schedule:
    - cron: 0 22 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: sudo update
        run: sudo apt-get update
      - name: Install Ghostscript
        run: sudo apt install ghostscript python3-tk
      - name: Check out repo
        uses: actions/checkout@v2 
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run postprocessing.py
        run: python postprocessing.py
        
      - name: Add and commit
        id: add_commit
        uses: EndBug/add-and-commit@v8
        with:
          committer_name: Automated
          committer_email: actions@users.noreply.github.com
          message: "Latest data"
