name: Run Interrupted Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-interrupted-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib arviz pymc scipy statsmodels datawrapper

    - name: Run Interrupted.py
      env:
        DATAWRAPPER_API: ${{ secrets.DATAWRAPPER_API }}
      run: python Interrupted.py
