name: Interrupted Time Series Analysis Workflow

on:
  push:
    paths:
      - 'Interrupted time series analysis.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pandas geopandas numpy matplotlib arviz pymc3 statsmodels scipy orbit-ml

      - name: Run script
        run: python 'Interrupted time series analysis.py'
