name: Run Python Script on GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  execute-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install pandas matplotlib numpy orbit-ml

    - name: Run Python Script
      run: python "Interrupted time series analysis-Filtered data-Orbit Model.py"
